# Generated by Django 5.2.7 on 2025-11-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('skin_type', models.CharField(max_length=100)),
                ('ingredients', models.CharField(max_length=1000)),
                ('purpose', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Items',
        ),
    ]
